os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: WHIR.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
xcode_scheme: WHIR
before_install:
- openssl aes-256-cbc -K $encrypted_fb2b8d187e4d_key -iv $encrypted_fb2b8d187e4d_iv
  -in keys.plist.enc -out WHIR/Resources/keys.plist
  -d
- pod install
after_success:
- bash <(curl -s https://codecov.io/bash) -t f3e1b970-eddf-4a5a-add3-267a5f5ec975
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af1e1ea78140e89f660b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
