os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: WHIR.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
xcode_scheme: WHIR
before_install:
- openssl aes-256-cbc -K $encrypted_fb2b8d187e4d_key -iv $encrypted_fb2b8d187e4d_iv
  -in keys.plist.enc -out WHIR/Resources/keys.plist
  -d
after_success:
  - bash <(curl -s https://codecov.io/bash)
