os: osx
language: objective-c
osx_image: xcode10
env:
  global:
  - WORKSPACE="WHIR.xcworkspace"
  matrix:
  - PLATFORM="iOS" SCHEME="WHIR" DESTINATION='platform=iOS Simulator,name=iPhone 8'
before_install:
- openssl aes-256-cbc -K $encrypted_fb2b8d187e4d_key -iv $encrypted_fb2b8d187e4d_iv
  -in keys.plist.enc -out WHIR/keys.plist -d
- gem install xcpretty
before_script:
- pod install
script:
- set -o pipefail && xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME"
  -destination "$DESTINATION" | xcpretty
